In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Arrays

In [2]:
my_array = make_array(1, 2, 3, 4)

In [3]:
my_array

array([1, 2, 3, 4])

In [4]:
len(my_array)

4

In [5]:
sum(my_array)

10

In [6]:
sum(my_array) / len(my_array)

2.5

In [7]:
np.average(my_array)

2.5

In [8]:
another = make_array(70, 60, 90, 80)

In [9]:
my_array + another

array([71, 62, 93, 84])

In [10]:
yet_another = make_array(5, 6, 7)

In [11]:
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [12]:
tunas = make_array('bluefin', 'albacore', 'jim')
tunas

array(['bluefin', 'albacore', 'jim'],
      dtype='<U8')

In [13]:
tunas * 4

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> dtype('<U8')

In [14]:
tunas.item(0) # NOTE: indexing starts at 0!

'bluefin'

In [15]:
tunas.item(2)

'jim'

In [16]:
tunas.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

## Columns of Tables are Arrays ##

In [17]:
nba = Table.read_table('nba_salaries.csv').relabeled(3, 'SALARY')
warriors = nba.where('TEAM', 'Golden State Warriors')

In [18]:
warriors

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [19]:
warriors.select('SALARY')

SALARY
15.501
14.2609
13.8
11.7105
11.3708
7.00847
5.54373
3.8734
3.815
2.5
... (4 rows omitted)

In [20]:
warriors.column('SALARY')

array([ 15.501   ,  14.26087 ,  13.8     ,  11.710456,  11.370786,
         7.008475,   5.543725,   3.873398,   3.815   ,   2.5     ,
         2.008748,   1.270964,   1.13196 ,   0.289755])

In [21]:
np.average(warriors.column('SALARY'))

6.7203669285714298

In [22]:
raptors = nba.where('TEAM', 'Toronto Raptors')

In [23]:
np.average(warriors.column('SALARY')) - np.average(raptors.column('SALARY'))

2.3278598697479005

## Ranges ##

In [24]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [26]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [27]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

# Ways to Create a Table #

## Creating a Table from Scratch ##

In [30]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [31]:
Table()

In [32]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [33]:
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [ ]:
southside

In [ ]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

In [ ]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

## Reading a Table from a File  ##

In [ ]:
du_bois = Table.read_table('du_bois.csv')
du_bois

In [ ]:
du_bois.column('ACTUAL AVERAGE')

In [ ]:
du_bois.column('FOOD')

In [ ]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

In [ ]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_columns('Food $', food_dollars)

In [ ]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

In [ ]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

du_bois = du_bois.with_columns('Food $', food_dollars)

du_bois

In [ ]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

In [ ]:
du_bois.labels

In [ ]:
du_bois.num_rows

In [ ]:
du_bois.num_columns